### ISSUE TITLE
panic: AttributeTypes on non-object Type

### ISSUE THREAD

**Issue by dennis-grunert** [tfsec/tfsec#142]
```
tfsec --version
v0.23.2
```

Running `tfsec` on this terraform file
```HCL
// BAD
locals {
  map_A = {
    example = "A"
  }
  map_B = {
    example = "B"
  }

  set_containing_A       = [local.map_A]
  set_containing_A_and_B = false ? local.set_containing_A : concat(local.set_containing_A, [local.map_B])
}
```

results in the error

```
panic: AttributeTypes on non-object Type

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Type.AttributeTypes(...)
	/private/tmp/tfsec-20200724-16953-cx23dz/tfsec-0.23.2/vendor/github.com/zclconf/go-cty/cty/object_type.go:134
github.com/zclconf/go-cty/cty/convert.unifyObjectTypesToMap(0xc00021e2f0, 0x2, 0x2, 0xc00017c701, 0x0, 0x17f5458, 0xc0001c0260, 0x3, 0x3)
	/private/tmp/tfsec-20200724-16953-cx23dz/tfsec-0.23.2/vendor/github.com/zclconf/go-cty/cty/convert/unify.go:224 +0x59b
github.com/zclconf/go-cty/cty/convert.unifyTupleTypesToList(0xc00021e2f0, 0x2, 0x2, 0x1, 0xc00000db70, 0x1, 0x1, 0xc0000189d5, 0x5)
	/private/tmp/tfsec-20200724-16953-cx23dz/tfsec-0.23.2/vendor/github.com/zclconf/go-cty/cty/convert/unify.go:343 +0x334
github.com/zclconf/go-cty/cty/convert.unifyTupleTypes(0xc00021e2f0, 0x2, 0x2, 0xc000210001, 0xc00021e0f0, 0x1228997, 0x0, 0x0, 0x0)
	/private/tmp/tfsec-20200724-16953-cx23dz/tfsec-0.23.2/vendor/github.com/zclconf/go-cty/cty/convert/unify.go:274 +0x6ab
github.com/zclconf/go-cty/cty/convert.unify(0xc00021e2f0, 0x2, 0x2, 0xc0001c0201, 0x1529900, 0x17f5458, 0x0, 0x0, 0x0)
	/private/tmp/tfsec-20200724-16953-cx23dz/tfsec-0.23.2/vendor/github.com/zclconf/go-cty/cty/convert/unify.go:55 +0x509
github.com/zclconf/go-cty/cty/convert.UnifyUnsafe(...)
	/private/tmp/tfsec-20200724-16953-cx23dz/tfsec-0.23.2/vendor/github.com/zclconf/go-cty/cty/convert/public.go:82
github.com/hashicorp/hcl/v2/hclsyntax.(*ConditionalExpr).Value(0xc0001230a0, 0xc00000df40, 0xc0000189c0, 0x10, 0xc00021e750, 0xc0001c0100, 0x0, 0x0, 0x0)
	/private/tmp/tfsec-20200724-16953-cx23dz/tfsec-0.23.2/vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression.go:515 +0x1d57
github.com/liamg/tfsec/internal/app/tfsec/parser.(*Parser).readValues(0xc00021fb40, 0xc00000df40, 0xc000133380, 0x14505bf, 0x6, 0xc00000e748, 0x1)
	/private/tmp/tfsec-20200724-16953-cx23dz/tfsec-0.23.2/internal/app/tfsec/parser/parser.go:316 +0x15e
github.com/liamg/tfsec/internal/app/tfsec/parser.(*Parser).getValuesByBlockType(0xc00021fb40, 0xc00000df40, 0xc00000e6a0, 0x1, 0x1, 0x14505bf, 0x6, 0x0, 0x15299c0, 0xc00000e740, ...)
	/private/tmp/tfsec-20200724-16953-cx23dz/tfsec-0.23.2/internal/app/tfsec/parser/parser.go:357 +0x87b
github.com/liamg/tfsec/internal/app/tfsec/parser.(*Parser).buildEvaluationContext(0xc00021fb40, 0xc00000e6a0, 0x1, 0x1, 0xc00001a2d0, 0x29, 0xc00017a900, 0x1, 0xc00021f6c0, 0xc00021f690, ...)
	/private/tmp/tfsec-20200724-16953-cx23dz/tfsec-0.23.2/internal/app/tfsec/parser/parser.go:178 +0xb5e
github.com/liamg/tfsec/internal/app/tfsec/parser.(*Parser).ParseDirectory(0xc00021fb40, 0xc00001a2d0, 0x29, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00006624c, 0xffffffffffffffff, ...)
	/private/tmp/tfsec-20200724-16953-cx23dz/tfsec-0.23.2/internal/app/tfsec/parser/parser.go:86 +0x4a1
main.glob..func2(0x17c6ee0, 0xc00017c4c0, 0x1, 0x1)
	/private/tmp/tfsec-20200724-16953-cx23dz/tfsec-0.23.2/cmd/tfsec/main.go:104 +0x415
github.com/spf13/cobra.(*Command).execute(0x17c6ee0, 0xc00000c090, 0x1, 0x1, 0x17c6ee0, 0xc00000c090)
	/private/tmp/tfsec-20200724-16953-cx23dz/tfsec-0.23.2/vendor/github.com/spf13/cobra/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x17c6ee0, 0x14, 0xc00012ff78, 0x10056cf)
	/private/tmp/tfsec-20200724-16953-cx23dz/tfsec-0.23.2/vendor/github.com/spf13/cobra/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/private/tmp/tfsec-20200724-16953-cx23dz/tfsec-0.23.2/vendor/github.com/spf13/cobra/command.go:887
main.main()
	/private/tmp/tfsec-20200724-16953-cx23dz/tfsec-0.23.2/cmd/tfsec/main.go:40 +0x31
```

Removing the intermediate variable `set_containing_A`

```HCL
// GOOD
locals {
  map_A = {
    example = "A"
  }
  map_B = {
    example = "B"
  }

  set_containing_A_and_B = false ? [local.map_A] : concat([local.map_A], [local.map_B])
}
```

or removing the ternary operator
```HCL
// GOOD
locals {
  map_A = {
    example = "A"
  }
  map_B = {
    example = "B"
  }

  set_containing_A       = [local.map_A]
  set_containing_A_and_B = concat(local.set_containing_A, [local.map_B])
}
```

works just fine.

**Comment by owenrumney** [comment]
looks like current version is correctly processing this, so will close
```
  times
  ------------------------------------------
  disk i/o             455.566µs
  parsing HCL          9.202µs
  evaluating values    215.794µs
  running checks       37.204µs

  counts
  ------------------------------------------
  files loaded         1
  blocks               1
  evaluated blocks     1
  modules              0
  module blocks        0

No problems detected!
```
