### ISSUE TITLE
Segfault on 0.24.1

### ISSUE THREAD

**Issue by clar-cmp** [tfsec/tfsec#143]
Just via running `tfsec` with no arguments on Darwin, using released binary.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x11b4776]

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Type.Equals(...)
        /home/travis/gopath/src/github.com/liamg/tfsec/vendor/github.com/zclconf/go-cty/cty/type.go:39
github.com/zclconf/go-cty/cty/convert.Convert(0x0, 0x0, 0x0, 0x0, 0x152e740, 0x17fc438, 0x0, 0x0, 0x0, 0x1, ...)
        /home/travis/gopath/src/github.com/liamg/tfsec/vendor/github.com/zclconf/go-cty/cty/convert/public.go:43 +0x26
github.com/hashicorp/hcl/v2/hclsyntax.(*FunctionCallExpr).Value(0xc0003e91d0, 0xc00079ef20, 0xc000049c00, 0x18a67d0, 0x8, 0x8, 0xc0005211b0, 0x203000, 0x203000)
        /home/travis/gopath/src/github.com/liamg/tfsec/vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression.go:371 +0x21d3
github.com/hashicorp/hcl/v2/hclsyntax.(*SplatExpr).Value(0xc0006ba790, 0xc00079ef20, 0xc00069d280, 0x3, 0xc000a9e730, 0xc0006ab890, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/liamg/tfsec/vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression.go:1277 +0x58
github.com/liamg/tfsec/internal/app/tfsec/parser.(*Parser).readValues(0xc000a9fb40, 0xc00079ef20, 0xc000a10270, 0xc0007ce9f0, 0xc0007cea50, 0x13f9d01, 0xc0007ce990)
        /home/travis/gopath/src/github.com/liamg/tfsec/internal/app/tfsec/parser/parser.go:316 +0x15e
github.com/liamg/tfsec/internal/app/tfsec/parser.(*Parser).getValuesByBlockType(0xc000a9fb40, 0xc00079ef20, 0xc000a1a000, 0x104, 0x150, 0x14547a2, 0x8, 0x0, 0x152e800, 0xc000520e30, ...)
        /home/travis/gopath/src/github.com/liamg/tfsec/internal/app/tfsec/parser/parser.go:382 +0x1d4
github.com/liamg/tfsec/internal/app/tfsec/parser.(*Parser).buildEvaluationContext(0xc000a9fb40, 0xc000a1a000, 0x104, 0x150, 0xc000016420, 0x1a, 0xc000a0f1a0, 0x1, 0xc000a9f6c0, 0xc000a9f690, ...)
        /home/travis/gopath/src/github.com/liamg/tfsec/internal/app/tfsec/parser/parser.go:180 +0xd78
github.com/liamg/tfsec/internal/app/tfsec/parser.(*Parser).ParseDirectory(0xc00073fb40, 0xc000016420, 0x1a, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0000202ac, 0xffffffffffffffff, ...)
        /home/travis/gopath/src/github.com/liamg/tfsec/internal/app/tfsec/parser/parser.go:86 +0x4a1
main.glob..func2(0x17cdec0, 0xc000172560, 0x1, 0x1)
        /home/travis/gopath/src/github.com/liamg/tfsec/cmd/tfsec/main.go:104 +0x415
github.com/spf13/cobra.(*Command).execute(0x17cdec0, 0xc00000c090, 0x1, 0x1, 0x17cdec0, 0xc00000c090)
        /home/travis/gopath/src/github.com/liamg/tfsec/vendor/github.com/spf13/cobra/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x17cdec0, 0x14, 0xc000123f78, 0x100548f)
        /home/travis/gopath/src/github.com/liamg/tfsec/vendor/github.com/spf13/cobra/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /home/travis/gopath/src/github.com/liamg/tfsec/vendor/github.com/spf13/cobra/command.go:887
main.main()
        /home/travis/gopath/src/github.com/liamg/tfsec/cmd/tfsec/main.go:40 +0x31
```

**Comment by clar-cmp** [comment]
Just verified the last working version without this bug is 0.22.0.

**Comment by mabelleeyanhwa** [comment]
I get the same error
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x11c36c6]

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Type.Equals(...)
        /private/tmp/tfsec-20200818-74834-tvvw6y/tfsec-0.23.2/vendor/github.com/zclconf/go-cty/cty/type.go:39
github.com/zclconf/go-cty/cty/convert.Convert(0x0, 0x0, 0x0, 0x0, 0x14eb740, 0x173d1d0, 0x0, 0x0, 0x0, 0x173cfa0, ...)
        /private/tmp/tfsec-20200818-74834-tvvw6y/tfsec-0.23.2/vendor/github.com/zclconf/go-cty/cty/convert/public.go:43 +0x26
github.com/hashicorp/hcl/v2/hclsyntax.(*FunctionCallExpr).Value(0xc000256000, 0xc000262240, 0xc00029e658, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /private/tmp/tfsec-20200818-74834-tvvw6y/tfsec-0.23.2/vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression.go:371 +0x21d4
github.com/liamg/tfsec/internal/app/tfsec/parser.(*Parser).readValues(0xc00029fb48, 0xc000262240, 0xc00020eea0, 0xc000217860, 0x0, 0xc000180700, 0x1)
        /private/tmp/tfsec-20200818-74834-tvvw6y/tfsec-0.23.2/internal/app/tfsec/parser/parser.go:316 +0x166
github.com/liamg/tfsec/internal/app/tfsec/parser.(*Parser).getValuesByBlockType(0xc00029fb48, 0xc000262240, 0xc000216900, 0x5, 0x6, 0x145a463, 0x8, 0x0, 0x14eb800, 0xc000180790, ...)
        /private/tmp/tfsec-20200818-74834-tvvw6y/tfsec-0.23.2/internal/app/tfsec/parser/parser.go:382 +0x1e5
github.com/liamg/tfsec/internal/app/tfsec/parser.(*Parser).buildEvaluationContext(0xc00029fb48, 0xc000216900, 0x5, 0x6, 0xc000198280, 0x74, 0xc000216930, 0x1, 0xc00029f6c8, 0xc00029f698, ...)
        /private/tmp/tfsec-20200818-74834-tvvw6y/tfsec-0.23.2/internal/app/tfsec/parser/parser.go:180 +0xda5
github.com/liamg/tfsec/internal/app/tfsec/parser.(*Parser).ParseDirectory(0xc00029fb48, 0xc000198280, 0x74, 0x0, 0x0, 0x0, 0x0, 0x0, 0x101499b, 0xffffffffffffffff, ...)
        /private/tmp/tfsec-20200818-74834-tvvw6y/tfsec-0.23.2/internal/app/tfsec/parser/parser.go:86 +0x4a5
main.glob..func2(0x17082a0, 0xc000218340, 0x1, 0x1)
        /private/tmp/tfsec-20200818-74834-tvvw6y/tfsec-0.23.2/cmd/tfsec/main.go:104 +0x427
github.com/spf13/cobra.(*Command).execute(0x17082a0, 0xc00019a010, 0x1, 0x1, 0x17082a0, 0xc00019a010)
        /private/tmp/tfsec-20200818-74834-tvvw6y/tfsec-0.23.2/vendor/github.com/spf13/cobra/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x17082a0, 0x14, 0xc0001bff78, 0x1005e85)
        /private/tmp/tfsec-20200818-74834-tvvw6y/tfsec-0.23.2/vendor/github.com/spf13/cobra/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /private/tmp/tfsec-20200818-74834-tvvw6y/tfsec-0.23.2/vendor/github.com/spf13/cobra/command.go:887
main.main()
        /private/tmp/tfsec-20200818-74834-tvvw6y/tfsec-0.23.2/cmd/tfsec/main.go:40 +0x31```


the code that causes this error is something like this:

```
resource "aws_lb_target_group_attachment" "alb_attach_to_vpclink" {
  target_group_arn = var.target_group.arn
  target_id        = data.aws_network_interface.alb[count.index].private_ip
  port             = 80
}

data "aws_network_interface" "alb" {
  filter {
    name = "description"
    values = ["ELB app/${var.alb.name}/*"]
  }

  filter {
    name = "subnet-id"
    values = [var.subnets[count.index].id]
  }
}

```

**Comment by mabelleeyanhwa** [comment]
Commenting out ```count = length(data.aws_network_interface.alb)``` fixes the error but I need this line.

**Comment by MattMencel** [comment]
I've discovered I'm having a similar issue. I've tried the latest 0.25.0 version with the same result.

```
> tfsec .
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x11b48a6]

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Type.Equals(...)
        /home/travis/gopath/src/github.com/liamg/tfsec/vendor/github.com/zclconf/go-cty/cty/type.go:39
github.com/zclconf/go-cty/cty/convert.Convert(0x0, 0x0, 0x0, 0x0, 0x152f920, 0x17fd458, 0x0, 0x0, 0x0, 0x152f8e0, ...)
        /home/travis/gopath/src/github.com/liamg/tfsec/vendor/github.com/zclconf/go-cty/cty/convert/public.go:43 +0x26
github.com/hashicorp/hcl/v2/hclsyntax.(*FunctionCallExpr).Value(0xc0002e6a50, 0xc0002666a0, 0xc000700000, 0x18b8108, 0x8, 0x8, 0xc0004e2b78, 0x203000, 0x203000)
        /home/travis/gopath/src/github.com/liamg/tfsec/vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression.go:371 +0x21d3
github.com/hashicorp/hcl/v2/hclsyntax.(*SplatExpr).Value(0xc00033ac60, 0xc0002666a0, 0x145483d, 0x5, 0xc0001e0be8, 0xc0004e2b01, 0x1, 0x1, 0xc000407e00)
        /home/travis/gopath/src/github.com/liamg/tfsec/vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression.go:1277 +0x58
github.com/liamg/tfsec/internal/app/tfsec/parser.(*Parser).getValuesByBlockType(0xc0001c48b8, 0xc0002666a0, 0xc000312d80, 0x1e, 0x30, 0x1454d32, 0x6, 0x0, 0x152f9e0, 0xc0004e2b78, ...)
        /home/travis/gopath/src/github.com/liamg/tfsec/internal/app/tfsec/parser/parser.go:354 +0x780
github.com/liamg/tfsec/internal/app/tfsec/parser.(*Parser).buildEvaluationContext(0xc0001c48b8, 0xc000312d80, 0x1e, 0x30, 0xc0000123f0, 0x65, 0xc0001c4948, 0x0, 0xc0001c5688, 0xc0001c5658, ...)
        /home/travis/gopath/src/github.com/liamg/tfsec/internal/app/tfsec/parser/parser.go:189 +0xe7f
github.com/liamg/tfsec/internal/app/tfsec/parser.(*Parser).parseModuleBlock(0xc0000b5b80, 0xc00014fba0, 0xc0001d62e0, 0xc000076180, 0x5e, 0xc0001c5688, 0xc0001c5658, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/liamg/tfsec/internal/app/tfsec/parser/parser.go:295 +0x9ff
github.com/liamg/tfsec/internal/app/tfsec/parser.(*Parser).buildEvaluationContext(0xc0001c5b80, 0xc00017ac60, 0x5, 0x6, 0xc000076180, 0x5e, 0xc00017ac90, 0x1, 0xc0001c5688, 0xc0001c5658, ...)
        /home/travis/gopath/src/github.com/liamg/tfsec/internal/app/tfsec/parser/parser.go:205 +0x6ed
github.com/liamg/tfsec/internal/app/tfsec/parser.(*Parser).ParseDirectory(0xc00021fb80, 0xc000076180, 0x5e, 0x0, 0x0, 0x0, 0x0, 0x0, 0x203000, 0xc000162100, ...)
        /home/travis/gopath/src/github.com/liamg/tfsec/internal/app/tfsec/parser/parser.go:86 +0x4a1
main.glob..func2(0x17ceee0, 0xc00017c580, 0x1, 0x1)
        /home/travis/gopath/src/github.com/liamg/tfsec/cmd/tfsec/main.go:119 +0x455
github.com/spf13/cobra.(*Command).execute(0x17ceee0, 0xc00000c090, 0x1, 0x1, 0x17ceee0, 0xc00000c090)
        /home/travis/gopath/src/github.com/liamg/tfsec/vendor/github.com/spf13/cobra/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x17ceee0, 0xf, 0xc000135f78, 0x100548f)
        /home/travis/gopath/src/github.com/liamg/tfsec/vendor/github.com/spf13/cobra/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /home/travis/gopath/src/github.com/liamg/tfsec/vendor/github.com/spf13/cobra/command.go:887
main.main()
        /home/travis/gopath/src/github.com/liamg/tfsec/cmd/tfsec/main.go:42 +0x31
```

I've tracked it down to this bit of code in a module. If I comment the kusto cluster resource out, tfsec passes.

``` terraform
variable "adx" { type = map(any) }
variable "resource_groups" { type = map(any) }

resource "azurerm_kusto_cluster" "adx" {
  for_each = var.adx.clusters

  name                = each.key
  location            = each.value.location
  resource_group_name = var.resource_groups[each.value.location].name

  optimized_auto_scale {
    maximum_instances = each.value.maximum_instances
    minimum_instances = each.value.minimum_instances
  }

  sku {
    name     = each.value.sku_name
    capacity = each.value.capacity
  }

  tags = var.tags
}
```

`var.adx.clusters` is a complex object...

``` yaml
adx:
  clusters:
    nonprod1:
      location: eastus2
      resource_group_name: nonprod-eastus2-shared
      maximum_instances: 5
      minimum_instances: 2
      sku_name: Standard_L4s
      capacity: 2
      databases:
        qa-eastus2:
          hot_cache_period: P31D # cache period set to 31 day
          soft_delete_period: P3650D # delete period set to 3650 day
    nonprod2:
      location: eastus2
      resource_group_name: nonprod-eastus2-shared
      maximum_instances: 5
      minimum_instances: 2
      sku_name: Standard_L4s
      capacity: 2
      databases:
        ci-eastus2:
          hot_cache_period: P31D # cache period set to 31 day
          soft_delete_period: P3650D # delete period set to 3650 day
        qa-eastus2:
          hot_cache_period: P31D # cache period set to 31 day
          soft_delete_period: P3650D # delete period set to 3650 day
```

**Comment by michal-franc** [comment]
Verified on `v0.39.10` no longer happening
