### ISSUE TITLE
Panic processing values() function call

### ISSUE THREAD

**Issue by mjjones1** [tfsec/tfsec#156]
The following 12 line Terraform file causes tfsec v0.25.0 (and also earlier versions) to crash. Note that this code was whittled down from valid Terraform to the simplest code that causes the crash:
```
resource aws_subnet this {
  tags = merge(local.tags, {
    Name = "${local.name}-my-subnet-${each.key}"
  })
  lifecycle {
    ignore_changes = [tags]
  }
}

module foo {
  subnets = values(aws_subnet.this)[*].id
}
```

The crash is:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5b6eb6]

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Type.Equals(...)
	/home/travis/gopath/src/github.com/liamg/tfsec/vendor/github.com/zclconf/go-cty/cty/type.go:39
github.com/zclconf/go-cty/cty/convert.Convert(0x0, 0x0, 0x0, 0x0, 0x92c000, 0xbf56c0, 0x0, 0x0, 0x0, 0x1b, ...)
	/home/travis/gopath/src/github.com/liamg/tfsec/vendor/github.com/zclconf/go-cty/cty/convert/public.go:43 +0x26
github.com/hashicorp/hcl/v2/hclsyntax.(*FunctionCallExpr).Value(0xc0002280f0, 0xc00000dde0, 0x203000, 0x203000, 0x203000, 0x203000, 0x203000, 0xffffffffffffffff, 0x0)
	/home/travis/gopath/src/github.com/liamg/tfsec/vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression.go:371 +0x21d3
github.com/hashicorp/hcl/v2/hclsyntax.(*SplatExpr).Value(0xc000194bb0, 0xc00000dde0, 0xc00029eaf0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/liamg/tfsec/vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression.go:1277 +0x58
github.com/liamg/tfsec/internal/app/tfsec/parser.(*Parser).parseModuleBlock(0xc00029fb80, 0xc0001b91e0, 0xc00000dde0, 0xc00001a164, 0x16, 0xc00029f688, 0xc00029f658, 0x0, 0x0, 0x0, ...)
<snip>
```

I changed the code to avoid using splat:
```
resource aws_subnet this {
  tags = merge(local.tags, {
    Name = "${local.name}-my-subnet-${each.key}"
  })
  lifecycle {
    ignore_changes = [tags]
  }
}

module foo {
  subnets = [for v in values(aws_subnet.this): v["id"]]
}
```

tfsec still crashes:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5b6eb6]

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Type.Equals(...)
	/home/travis/gopath/src/github.com/liamg/tfsec/vendor/github.com/zclconf/go-cty/cty/type.go:39
github.com/zclconf/go-cty/cty/convert.Convert(0x0, 0x0, 0x0, 0x0, 0x92c000, 0xbf56c0, 0x0, 0x0, 0x0, 0xc00014e140, ...)
	/home/travis/gopath/src/github.com/liamg/tfsec/vendor/github.com/zclconf/go-cty/cty/convert/public.go:43 +0x26
github.com/hashicorp/hcl/v2/hclsyntax.(*FunctionCallExpr).Value(0xc0001a80f0, 0xc00000de40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/liamg/tfsec/vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression.go:371 +0x21d3
github.com/hashicorp/hcl/v2/hclsyntax.(*ForExpr).Value(0xc00014e140, 0xc00000de40, 0xc00021eaf0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/liamg/tfsec/vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression.go:925 +0x59
github.com/liamg/tfsec/internal/app/tfsec/parser.(*Parser).parseModuleBlock(0xc00021fb80, 0xc00015eea0, 0xc00000de40, 0xc00001a164, 0x16, 0xc00021f688, 0xc00021f658, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/liamg/tfsec/internal/app/tfsec/parser/parser.go:245 +0x189
github.com/liamg/tfsec/internal/app/tfsec/parser.(*Parser).buildEvaluationContext(0xc00021fb80, 0xc0001685c0, 0x2, 0x2, 0xc00001a164, 0x16, 0xc000166930, 0x1, 0xc00021f688, 0xc00021f658, ...)
<snip>
```

I changed the code to avoid using the values() function call:
```
resource aws_subnet this {
  tags = merge(local.tags, {
    Name = "${local.name}-my-subnet-${each.key}"
  })
  lifecycle {
    ignore_changes = [tags]
  }
}

module foo {
  subnets = [for k, v in aws_subnet.this: v["id"]]
}
```

tfsec no longer crashes. It looks like a problem processing the values() function call.

**Comment by paul-pop** [comment]
I had exactly the same issue and using the for loop fixed it for me as well. Seems to be somewhat related to #143.

**Comment by uolter** [comment]
I have the same identical error parsing this file:
[azurerm_application_gateway](https://github.com/pagopa/io-infrastructure-modules-new/blob/master/azurerm_application_gateway/main.tf)

The fix that I've applied is in the file
vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression.go at line 362 I changed this check:

```
} else if val != cty.NilVal {
			var argDiags hcl.Diagnostics
			val, argDiags = argExpr.Value(ctx)
			if len(argDiags) > 0 {
				diags = append(diags, argDiags...)
			}
```

it was just:
```
} else {
			var argDiags hcl.Diagnostics
			val, argDiags = argExpr.Value(ctx)
			if len(argDiags) > 0 {
				diags = append(diags, argDiags...)
			}
```

I'm not sure this correct. I've many doubs.

**Comment by clar-cmp** [comment]
This project is clearly actively maintained but this is still a major bug that prevents me from updating... :|

**Comment by owenrumney** [comment]
Hey @mjjones1 , @uolter @clar-cmp  - I'm looking at this now and I can't reproduce. I've use

```
resource aws_subnet this {
  tags = merge(local.tags, {
    Name = "${local.name}-my-subnet-${each.key}"
  })
  lifecycle {
    ignore_changes = [tags]
  }
}

module foo {
  subnets = values(aws_subnet.this)[*].id
}
```

and get the following output
```
WARNING: Failed to load module: could not read module source attribute at /Users/owen/go/src/github.com/tfsec/tfsec/example/issue156/main.tf:10-12

  times
  ------------------------------------------
  disk i/o                    535.191µs
  parsing HCL             10.391µs
  evaluating values    27.364µs
  running checks       112.184µs

  counts
  ------------------------------------------
  files loaded               1
  blocks                       2
  evaluated blocks      2
  modules                    0
  module blocks          0

No problems detected!
```

I'm confused by the module and what it is aiming to achieve without the required attributes. Can you confirm whether this is still a live issue with the latest version?

**Comment by mjjones1** [comment]
Hi Owen, I can confirm that with the latest version I no longer see this problem. We reenabled tfsec in our project some time ago and have not seen a problem since. This was a weird problem, but all good now!! Thanks for taking the time to investigate.

**Comment by owenrumney** [comment]
That's great to hear - I do apologise for how long it took us to get to this - we're actively working on tfsec so please do shout with any future issues
