### ISSUE TITLE
AWS051 nil pointer dereference

### ISSUE THREAD

**Issue by particleflux** [tfsec/tfsec#700]
**Describe the bug**
_runtime error: invalid memory address or nil pointer dereference_ error when running AWS051

Seems to be related to the fact that the `key_id` is referenced via a datasource

(https://github.com/tfsec/tfsec/blob/v0.39.23/internal/app/tfsec/checks/aws051.go#L50 this seems to be the affected line)

**To Reproduce**

1. Get the attached zip [tfsec-aws051.zip](https://github.com/tfsec/tfsec/files/6365423/tfsec-aws051.zip)
2. run `terraform init` in test dir
3. run `tfsec .` in test dir

**Expected behavior**
Test should pass

**Stacktrace**

```
[DEBUG][2021-04-23 14:19:59.801777373 +0200 CEST m=+0.020743313] Stack trace for failed AWS051 check:
goroutine 1 [running]:
runtime/debug.Stack(0x9e74a0, 0xc00000e020, 0x944099)
        /opt/hostedtoolcache/go/1.16.2/x64/src/runtime/debug/stack.go:24 +0x9f
github.com/tfsec/tfsec/internal/app/tfsec/scanner.(*Check).Run.func1(0xc0004e2ea0)
        /home/runner/work/tfsec/tfsec/internal/app/tfsec/scanner/check.go:76 +0x125
panic(0x8c9c60, 0xcdbd00)
        /opt/hostedtoolcache/go/1.16.2/x64/src/runtime/panic.go:965 +0x1b9
github.com/zclconf/go-cty/cty.Type.FriendlyName(...)
        /home/runner/work/tfsec/tfsec/vendor/github.com/zclconf/go-cty/cty/type.go:47
github.com/hashicorp/hcl/v2/hclsyntax.(*ConditionalExpr).Value(0xc0001220e0, 0xc0004c8900, 0x8e04a0, 0xc000144401, 0xc0004e0540, 0xc0000caf10, 0x791e15, 0x8e04a0, 0xc0004e0540)
        /home/runner/work/tfsec/tfsec/vendor/github.com/hashicorp/hcl/v2/hclsyntax/expression.go:590 +0x2c0
github.com/tfsec/tfsec/internal/app/tfsec/parser.(*Attribute).Value(0xc0004e0530, 0xc000385f80, 0xc000144380, 0xc000144450, 0x0)
        /home/runner/work/tfsec/tfsec/internal/app/tfsec/parser/attribute.go:40 +0x4d
github.com/tfsec/tfsec/internal/app/tfsec/parser.(*Attribute).IsEmpty(0xc0004e0530, 0x932897)
        /home/runner/work/tfsec/tfsec/internal/app/tfsec/parser/attribute.go:223 +0x2f
github.com/tfsec/tfsec/internal/app/tfsec/checks.init.45.func1(0xc0004e2ea0, 0xc0000b5b30, 0xc000618798, 0xf, 0xc0000cb2e0, 0x2)
        /home/runner/work/tfsec/tfsec/internal/app/tfsec/checks/aws051.go:50 +0x855
github.com/tfsec/tfsec/internal/app/tfsec/scanner.(*Check).Run(0xc0004e2ea0, 0xc0000b5b30, 0xc000618798, 0x0, 0x0, 0x0)
        /home/runner/work/tfsec/tfsec/internal/app/tfsec/scanner/check.go:79 +0xa4
github.com/tfsec/tfsec/internal/app/tfsec/scanner.(*Scanner).Scan.func1(0xc0000cb888, 0xc000618798, 0xc0000cb855, 0xc0000cb8a8, 0xc0000cb856, 0xc0000cba7e, 0x0, 0x0, 0x0, 0x92a81b, ...)
        /home/runner/work/tfsec/tfsec/internal/app/tfsec/scanner/scanner.go:71 +0x2ff
github.com/tfsec/tfsec/internal/app/tfsec/scanner.(*Scanner).Scan(0xc0000cba7e, 0xc000088400, 0x78, 0x80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/runner/work/tfsec/tfsec/internal/app/tfsec/scanner/scanner.go:86 +0x318
main.glob..func2(0xce3300, 0xc00007b6a0, 0x1, 0x2)
        /home/runner/work/tfsec/tfsec/cmd/tfsec/main.go:183 +0x827
github.com/spf13/cobra.(*Command).execute(0xce3300, 0xc000010190, 0x2, 0x2, 0xce3300, 0xc000010190)
        /home/runner/work/tfsec/tfsec/vendor/github.com/spf13/cobra/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xce3300, 0xc00005a778, 0xc000137f78, 0x4062e5)
        /home/runner/work/tfsec/tfsec/vendor/github.com/spf13/cobra/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/work/tfsec/tfsec/vendor/github.com/spf13/cobra/command.go:897
main.main()
        /home/runner/work/tfsec/tfsec/cmd/tfsec/main.go:70 +0x31

```

**Versions**
 - tfsec 0.39.23
 - terraform 0.14.7

**Comment by particleflux** [comment]
That PR does indeed fix the issue I reported, with the reproduction I did for the issue.

Sadly, not (completely) the issue I wanted to report :D

The original issue I had is slightly changed to this stacktrace on the PR branch:

```
WARNING: skipped AWS051 check due to error(s): value is null
[DEBUG][2021-04-23 20:04:51.213803884 +0200 CEST m=+0.024715396] Stack trace for failed AWS051 check:
goroutine 1 [running]:
runtime/debug.Stack(0x9e7b80, 0xc00000e020, 0x94424d)
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x9f
github.com/tfsec/tfsec/internal/app/tfsec/scanner.(*Check).Run.func1(0xc000a476c0)
        /home/stefan/src/tfsec/internal/app/tfsec/scanner/check.go:76 +0x125
panic(0x8ab9c0, 0x9df480)
        /usr/lib/go/src/runtime/panic.go:965 +0x1b9
github.com/zclconf/go-cty/cty.Value.AsString(0x9ef6c0, 0xc000014729, 0x0, 0x0, 0x0, 0x0)
        /home/stefan/src/tfsec/vendor/github.com/zclconf/go-cty/cty/value_ops.go:1254 +0x185
github.com/tfsec/tfsec/internal/app/tfsec/parser.(*Attribute).IsEmpty(0xc000a39760, 0x9329c2)
        /home/stefan/src/tfsec/internal/app/tfsec/parser/attribute.go:224 +0x3f2
github.com/tfsec/tfsec/internal/app/tfsec/checks.init.45.func1(0xc000a476c0, 0xc0000b1bc0, 0xc00000c4e0, 0xf, 0xc00059f2e0, 0x2)
        /home/stefan/src/tfsec/internal/app/tfsec/checks/aws051.go:50 +0x855
github.com/tfsec/tfsec/internal/app/tfsec/scanner.(*Check).Run(0xc000a476c0, 0xc0000b1bc0, 0xc00000c4e0, 0x0, 0x0, 0x0)
        /home/stefan/src/tfsec/internal/app/tfsec/scanner/check.go:79 +0xa4
github.com/tfsec/tfsec/internal/app/tfsec/scanner.(*Scanner).Scan.func1(0xc00059f888, 0xc00000c4e0, 0xc00059f855, 0xc00059f8a8, 0xc00059f856, 0xc00059fa7e, 0x0, 0x0, 0x0, 0x92a93d, ...)
        /home/stefan/src/tfsec/internal/app/tfsec/scanner/scanner.go:71 +0x2ff
github.com/tfsec/tfsec/internal/app/tfsec/scanner.(*Scanner).Scan(0xc00059fa7e, 0xc000680400, 0x78, 0x80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/stefan/src/tfsec/internal/app/tfsec/scanner/scanner.go:86 +0x318
main.glob..func2(0xce1340, 0xc00007b6a0, 0x1, 0x2)
        /home/stefan/src/tfsec/cmd/tfsec/main.go:183 +0x827
github.com/spf13/cobra.(*Command).execute(0xce1340, 0xc000010190, 0x2, 0x2, 0xce1340, 0xc000010190)
        /home/stefan/src/tfsec/vendor/github.com/spf13/cobra/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xce1340, 0xc00005a778, 0xc000137f78, 0x4062e5)
        /home/stefan/src/tfsec/vendor/github.com/spf13/cobra/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/stefan/src/tfsec/vendor/github.com/spf13/cobra/command.go:897
main.main()
        /home/stefan/src/tfsec/cmd/tfsec/main.go:70 +0x31
```

**Comment by owenrumney** [comment]
Yeah, I had a go at resolving it and introduced a raft of new bugs, I see the issue just looking for a cleaner fix

**Comment by owenrumney** [comment]
Hey @particleflux  - apologies for the delay, does this improve things for you? The problem seems to be that data requires some state to get the details which we just don't have access to, I've tried to gracefully recover from not being able to evaluate the value but it does end up with a cty.NilVal being returned. your example results in 

```
 go run ./cmd/tfsec ~/Downloads/tfsec-aws051/test  --verbose
[DEBUG][2021-04-30 08:58:39.348743 +0100 BST m=+0.002055076] Loading custom checks...
[DEBUG][2021-04-30 08:58:39.348921 +0100 BST m=+0.002232762] Using the default custom check folder
[DEBUG][2021-04-30 08:58:39.348927 +0100 BST m=+0.002238293] custom check directory set to /Users/owen/Downloads/tfsec-aws051/test/.tfsec
[DEBUG][2021-04-30 08:58:39.348938 +0100 BST m=+0.002249301] Custom checks loaded
[DEBUG][2021-04-30 08:58:39.348941 +0100 BST m=+0.002252916] checking for tfvars files using glob: /Users/owen/Downloads/tfsec-aws051/test/*.tfvars
[DEBUG][2021-04-30 08:58:39.349024 +0100 BST m=+0.002335489] Starting parser...
[DEBUG][2021-04-30 08:58:39.349031 +0100 BST m=+0.002342490] Finding Terraform subdirectories...
[DEBUG][2021-04-30 08:58:39.349101 +0100 BST m=+0.002412576] Found qualifying subdirectory containing .tf files: /Users/owen/Downloads/tfsec-aws051/test
[DEBUG][2021-04-30 08:58:39.349108 +0100 BST m=+0.002419585] Beginning parse for directory '/Users/owen/Downloads/tfsec-aws051/test'...
[DEBUG][2021-04-30 08:58:39.349431 +0100 BST m=+0.002742292] Added 2 blocks from /Users/owen/Downloads/tfsec-aws051/test/main.tf...
[DEBUG][2021-04-30 08:58:39.34944 +0100 BST m=+0.002752201] Project root set to '/Users/owen/Downloads/tfsec-aws051/test'...
[DEBUG][2021-04-30 08:58:39.349443 +0100 BST m=+0.002755004] Loading TFVars...
[DEBUG][2021-04-30 08:58:39.349447 +0100 BST m=+0.002759127] Loading module metadata...
[DEBUG][2021-04-30 08:58:39.349603 +0100 BST m=+0.002914926] Loading modules...
[DEBUG][2021-04-30 08:58:39.349833 +0100 BST m=+0.003144895] Added 3 blocks from /Users/owen/Downloads/tfsec-aws051/module/main.tf...
[DEBUG][2021-04-30 08:58:39.349848 +0100 BST m=+0.003160011] Loaded module '/Users/owen/Downloads/tfsec-aws051/module' (requested at /Users/owen/Downloads/tfsec-aws051/test/main.tf:5-10)
[DEBUG][2021-04-30 08:58:39.34986 +0100 BST m=+0.003171983] Evaluating expressions...
[DEBUG][2021-04-30 08:58:39.349891 +0100 BST m=+0.003202938] Starting iteration 1 of context evaluation...
[DEBUG][2021-04-30 08:58:39.349945 +0100 BST m=+0.003256818] Starting iteration 1 of context evaluation...
[DEBUG][2021-04-30 08:58:39.350169 +0100 BST m=+0.003480594] Starting iteration 2 of context evaluation...
[DEBUG][2021-04-30 08:58:39.350252 +0100 BST m=+0.003563977] Starting iteration 2 of context evaluation...
[DEBUG][2021-04-30 08:58:39.350285 +0100 BST m=+0.003596488] Module [test:/Users/owen/Downloads/tfsec-aws051/module] has already been seen
[DEBUG][2021-04-30 08:58:39.35029 +0100 BST m=+0.003601776] Starting iteration 3 of context evaluation...
[DEBUG][2021-04-30 08:58:39.350312 +0100 BST m=+0.003623227] Module [test:/Users/owen/Downloads/tfsec-aws051/module] has already been seen
[DEBUG][2021-04-30 08:58:39.350342 +0100 BST m=+0.003653915] Starting scanner...
[DEBUG][2021-04-30 08:58:39.350416 +0100 BST m=+0.003727990] Running check for GEN003 on module.module.test (/Users/owen/Downloads/tfsec-aws051/test/main.tf)...
[DEBUG][2021-04-30 08:58:39.350437 +0100 BST m=+0.003748241] Running check for GEN001 on variable.module.test:variable.encrypt (/Users/owen/Downloads/tfsec-aws051/module/main.tf)...
[DEBUG][2021-04-30 08:58:39.35046 +0100 BST m=+0.003771958] Running check for GEN001 on variable.module.test:variable.kms_key_id (/Users/owen/Downloads/tfsec-aws051/module/main.tf)...
[DEBUG][2021-04-30 08:58:39.350485 +0100 BST m=+0.003796512] Running check for AWS051 on resource.module.test:aws_rds_cluster.test (/Users/owen/Downloads/tfsec-aws051/module/main.tf)...
[DEBUG][2021-04-30 08:58:39.350576 +0100 BST m=+0.003888039] Running check for GEN003 on resource.module.test:aws_rds_cluster.test (/Users/owen/Downloads/tfsec-aws051/module/main.tf)...

  times
  ------------------------------------------
  disk i/o             713.914µs
  parsing HCL          18.09µs
  evaluating values    379.201µs
  running checks       232.179µs

  counts
  ------------------------------------------
  files loaded         2
  blocks               2
  evaluated blocks     5
  modules              1
  module blocks        3
  ignored checks       0

No problems detected!

```

**Comment by particleflux** [comment]
Yes, the current PR resolves the issue with the example and also with my original problem :+1:
